### PR TITLE
Fix .env handling when using "deploy function"

### PR DESCRIPTION
**Pull request by patheticcockroach**
I don't know when it was changed, but the proper hooks to create and delete the .env file when deploying an individual function are now `before:deploy:function:packageFunction` and `after:deploy:function:packageFunction`.

I'm also including hauboldj's patch to create/remove .env file when invoking locally (PR #7 ), as I used the online editor only and didn't know how to make a PR with just my commits.

### CODE REVIEW

**Comment by patheticcockroach** [comment]
About the new package/deploy plugin lifecycle: https://gist.github.com/HyperBrain/bba5c9698e92ac693bb461c99d6cfeec

**Comment by jthomerson** [comment]
@patheticcockroach I'm sorry for the extreme delay on this PR. I had written off this plugin as no longer useful since Lambda introduced support for environment variables and Serverless supported it. I'm curious if you're still using this plugin, and if so, what is the usecase? If it seems like it's still a necessary plugin, I'll look at merging the open PRs and shipping a release. Thanks!

**Comment by patheticcockroach** [comment]
Hi, yes I'm still using the plugin. TBH we never thought about using Lambda's environment variables for that purpose, nor about checking if Serverless had support for them, so we have quite a few projects at my company where we use this plugin + dotenv rather that Lambda's env variables.

I guess we'll migrate sooner than later (assuming Serverless's support for Lambda's env variables also covers "invoke local"), still having the plugin updated would be more convenient than patching it manually every time, as we currently do.

**Comment by jthomerson** [comment]
Thanks for the quick feedback. I rebased it, fixed it, merged it, and pushed it. Unfortunately because you'd used "master" as your branch name, that messed up the PR history a bit, but it's merged. I'll release 1.0.2 shortly and it will contain your fixes.

**Pull request closed without merging**
